//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicHelper.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Users = new HashSet<User>();
        }
    
        public int EventId { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public int EventMaxGuests { get; set; }
        public string EventName { get; set; }
        public string EventAdress { get; set; }
        public int SweissId { get; set; }
        public string EventCode { get; set; }
        public string EventDescription { get; set; }
        public int EventOwnerId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string UsersIdList { get; set; }
    
        public virtual Sweiss Sweiss { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
